version: "3.1"

volumes:
  pg_library:

services:
  library-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=modsen-books-service-db
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg_library:/var/lib/postgresql/data
    ports:
      - "5000:5432"

  library-service:
    restart: always
    build: .
    depends_on:
      - library-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-db:5432/modsen-books-service-db
